server:
  port: 8086

spring:
  application:
    name: notification-service
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:ecommerce-postgres}:${DB_PORT:5432}/${DB_NAME:ecommerce}
    username: ${DB_USERNAME:ecommerce_user}
    password: ${DB_PASSWORD:ecommerce_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  data:
    redis:
      host: ${REDIS_HOST:redis-service}
      port: ${REDIS_PORT:6379}
      database: 0
      timeout: 2000ms
      jedis:
        pool:
          max-total: 20
          max-wait: -1ms
          max-idle: 10
          min-idle: 2
  
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.bits.notification.event"
  
  # Email Configuration
  mail:
    host: ${MAIL_HOST:mailhog}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
        debug: true
  
  # Thymeleaf Configuration
  thymeleaf:
    cache: false
    mode: HTML

# JWT Configuration (same secret as other services)
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours

# Service registration
service:
  name: notification-service
  host: ${POD_IP:localhost}
  port: ${SERVER_PORT:8086}
  registration:
    ttl-seconds: 30
    refresh-interval-ms: 20000

# External Service Configuration
twilio:
  account-sid: ${TWILIO_ACCOUNT_SID:your-account-sid}
  auth-token: ${TWILIO_AUTH_TOKEN:your-auth-token}
  phone-number: ${TWILIO_PHONE_NUMBER:+1234567890}

firebase:
  config:
    path: ${FIREBASE_CONFIG_PATH:}

# Logging
logging:
  level:
    com.bits.notification: INFO
    org.springframework.cache: DEBUG
    org.springframework.security: DEBUG
    org.springframework.kafka: INFO
    org.springframework.transaction: DEBUG
    org.springframework.mail: DEBUG
    org.hibernate: WARN
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-}] %logger{36} - %msg%n"
  file:
    name: logs/notification-service.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/notification-service.%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      max-history: 10
      total-size-cap: 100MB

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      podname: ${HOSTNAME:unknown}


