package com.bits.order.enums;

public enum NotificationType {
    WELCOME, ORDER_CONFIRMATION, ORDER_SHIPPED, ORDER_DELIVERED, 
    PAYMENT_SUCCESS, PAYMENT_FAILED, INVENTORY_LOW_STOCK, 
    CART_ABANDONMENT, PROMOTIONAL, SYSTEM_ALERT, PASSWORD_RESET,
    ORDER_STATUS_UPDATE
}
