apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      tolerations:
        - operator: Exists
      containers:
        - name: fluent-bit
          image: cr.fluentbit.io/fluent/fluent-bit:2.2.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2020
              name: http
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: varlibcontainers
              mountPath: /var/log/containers
              readOnly: true
            - name: varlibpods
              mountPath: /var/log/pods
              readOnly: true
            - name: varlibdocker
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: config
              mountPath: /fluent-bit/etc/
          env:
            - name: FLUENT_BIT_CONFIG
              value: /fluent-bit/etc/fluent-bit.conf
      volumes:
        - name: varlibcontainers
          hostPath:
            path: /var/log/containers
        - name: varlibpods
          hostPath:
            path: /var/log/pods
        - name: varlibdocker
          hostPath:
            path: /var/lib/docker/containers
        - name: config
          configMap:
            name: fluent-bit-config
            items:
              - key: fluent-bit.conf
                path: fluent-bit.conf
              - key: parsers.conf
                path: parsers.conf
              - key: filters.lua
                path: filters.lua
