apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-ism
  namespace: logging
  labels:
    app: opensearch
data:
  policy.json: |
    {
      "policy": {
        "description": "Delete logs after 7 days",
        "default_state": "hot",
        "states": [
          {
            "name": "hot",
            "actions": [],
            "transitions": [
              {
                "state_name": "delete",
                "conditions": { "min_index_age": "7d" }
              }
            ]
          },
          {
            "name": "delete",
            "actions": [ { "delete": {} } ],
            "transitions": []
          }
        ]
      }
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: opensearch-setup
  namespace: logging
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: setup
          image: curlimages/curl:8.8.0
          env:
            - name: OPENSEARCH_URL
              value: http://opensearch.logging.svc.cluster.local:9200
          command: ["/bin/sh","-lc"]
          args:
            - |
              set -e
              echo "Waiting for OpenSearch..."
              until curl -s ${OPENSEARCH_URL} > /dev/null; do sleep 3; done
              echo "Applying ISM policy..."
              curl -s -X PUT "${OPENSEARCH_URL}/_plugins/_ism/policies/logs-7d-policy" \
                   -H 'Content-Type: application/json' \
                   --data-binary @/config/policy.json
              echo "Attaching ISM policy to index pattern logs-ai-loadbalancer-*"
              curl -s -X POST "${OPENSEARCH_URL}/_plugins/_ism/add/logs-ai-loadbalancer-*" \
                   -H 'Content-Type: application/json' \
                   -d '{"policy_id": "logs-7d-policy"}'
              echo "Done"
          volumeMounts:
            - name: policy
              mountPath: /config
      volumes:
        - name: policy
          configMap:
            name: opensearch-ism
            items:
              - key: policy.json
                path: policy.json
