apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: ai-loadbalancer
  labels:
    app: cart-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: cart-service
        image: cart-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        - name: SERVICE_HOST
          value: "cart-service"
        - name: REDIS_HOST
          value: "redis.ai-loadbalancer.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: KAFKA_BROKERS
          value: "kafka.ai-loadbalancer.svc.cluster.local:9092"
        - name: JWT_SECRET
          value: "mySecretKey123456789012345678901234567890123456789012345678901234567890"
        - name: JWT_EXPIRATION
          value: "86400000"
        - name: SERVER_PORT
          value: "8082"
        - name: AI_LOADBALANCER_URL
          value: "http://ai-loadbalancer-service.ai-loadbalancer.svc.cluster.local:8080"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: ai-loadbalancer
  labels:
    app: cart-service
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
  selector:
    app: cart-service
